typography_spectrum: 0.7303744936361909
color:
  brandStrength: 0.5451670160982758
  lightness: 0.5441957274451852
  saturation: 0.8858255362138152
  rhythmicContrast: 0.45693249185569584
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.4340933922212571
name: Jeff Hileman
navigation:
  - name: Libertarian
    url: 'https://www.johnsonweld.com/'
    type: external
  - name: Jeff Hileman
    url: www.jeffhileman.com
    type: external
title: A Libertarian USA
description: Looking for the lesser of two evils? Vote Gary Johnson
